/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.menu.Menu;
import Business.menu.MenuDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhuva
 */
    public class Addmenupanel extends javax.swing.JPanel {
        JPanel userProcessContainer;
        EcoSystem system;
        String restaurantName;
        Menu m;
        Restaurant res;
    
    public Addmenupanel(JPanel userProcessContainer, EcoSystem system, String restaurantName) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.restaurantName = restaurantName;
        initComponents();
        lbhotelname.setText(restaurantName);
        populatetable();
        
    }
   
    public void populatetable(){
        DefaultTableModel defaultmenutble = (DefaultTableModel) menutable.getModel();
        defaultmenutble.setRowCount(0);
        Restaurant ro1 = system.getRestaurantDirectory().findRestaurant(restaurantName);
        if(ro1.getMd()!=null){
            for(Menu m : ro1.getMd().getMenu()) {
                Object row[] = new Object[3];
                row[0] = m;
                row[1] = m.getItemPrice();
                row[2] = m.getQuantity();
                defaultmenutble.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbhotelname = new javax.swing.JLabel();
        lbmenuitems = new javax.swing.JLabel();
        lbItemPrice = new javax.swing.JLabel();
        menuitemtxt = new javax.swing.JTextField();
        itempricetxt = new javax.swing.JTextField();
        btaddmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menutable = new javax.swing.JTable();
        btback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbItemPrice1 = new javax.swing.JLabel();
        itemquantitytxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbmmt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbItemPrice2 = new javax.swing.JLabel();
        modbut = new javax.swing.JButton();
        txtmiq = new javax.swing.JTextField();
        txtmip = new javax.swing.JTextField();
        txtmmt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Menu");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 982, 51));

        lbhotelname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbhotelname.setText("Hotelname");
        add(lbhotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 99, -1, -1));

        lbmenuitems.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbmenuitems.setText("Menu Items");
        add(lbmenuitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 174, -1, -1));

        lbItemPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbItemPrice.setText("Item Price");
        add(lbItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 242, -1, -1));
        add(menuitemtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 176, 200, -1));

        itempricetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itempricetxtKeyTyped(evt);
            }
        });
        add(itempricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 244, 200, -1));

        btaddmenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btaddmenu.setText("Add Menu");
        btaddmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btaddmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddmenuActionPerformed(evt);
            }
        });
        add(btaddmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 306, -1, -1));

        menutable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Item Price", "Item Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menutable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 167, -1, 97));

        btback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btback.setText("Back");
        btback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 306, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Update Menu");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 306, -1, -1));

        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 982, 5));

        lbItemPrice1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbItemPrice1.setText("Quantity");
        add(lbItemPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 209, -1, -1));

        itemquantitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemquantitytxtKeyTyped(evt);
            }
        });
        add(itemquantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 211, 200, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modify Menu");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 980, 37));

        lbmmt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbmmt.setText("Modify Menu Items:");
        add(lbmmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Modify Item Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        lbItemPrice2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbItemPrice2.setText("Modify Item Quantity :");
        add(lbItemPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        modbut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modbut.setText("Modify");
        modbut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modbutActionPerformed(evt);
            }
        });
        add(modbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));
        add(txtmiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 166, -1));

        txtmip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmipKeyTyped(evt);
            }
        });
        add(txtmip, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 166, -1));
        add(txtmmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 166, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fourth.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void btaddmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddmenuActionPerformed
        try{
        String menuIt = menuitemtxt.getText();
        Double ip = Double.valueOf(itempricetxt.getText());
        Integer quantity= Integer.valueOf(itemquantitytxt.getText());
        Menu m = new Menu();
        m.setItemName(menuIt);
        m.setItemPrice(ip);
        m.setQuantity(quantity);
        Restaurant ro = system.getRestaurantDirectory().findRestaurant(restaurantName);
        if(ro.getMd() == null){
            MenuDirectory md = new MenuDirectory();
            ArrayList<Menu> am  = new ArrayList<>();
            am.add(m);
            md.setMenu(am);
            ro.setMd(md);  
        }
        else{
            MenuDirectory md =   ro.getMd();
            ArrayList<Menu> am  = ro.getMd().getMenu();
            am.add(m);
            md.setMenu(am);
            ro.setMd(md);
        }
        populatetable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please provide appropriate value to proceed"); 
        }
    }//GEN-LAST:event_btaddmenuActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        int selectedRow = menutable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        m = (Menu)menutable.getValueAt(selectedRow,0);
        txtmmt.setText(m.getItemName());
        txtmiq.setText(String.valueOf(m.getQuantity()));
        txtmip.setText(String.valueOf(m.getItemPrice()));
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null,"Please provide appropriate value to proceed");  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modbutActionPerformed
        try{
        m.setItemName(txtmmt.getText());
        m.setItemPrice(Double.valueOf(txtmip.getText()));
        m.setQuantity(Integer.parseInt(txtmiq.getText()));
        JOptionPane.showMessageDialog(null,"Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);                                       
        populatetable();
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null,"Please provide appropriate value to proceed");     
        }
    }//GEN-LAST:event_modbutActionPerformed

    private void itemquantitytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemquantitytxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if(!Character.isDigit(value)) {
            evt.consume();
        }
    }//GEN-LAST:event_itemquantitytxtKeyTyped

    private void itempricetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itempricetxtKeyTyped
    }//GEN-LAST:event_itempricetxtKeyTyped

    private void txtmipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmipKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if(!Character.isDigit(value)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtmipKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddmenu;
    private javax.swing.JButton btback;
    private javax.swing.JTextField itempricetxt;
    private javax.swing.JTextField itemquantitytxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbItemPrice;
    private javax.swing.JLabel lbItemPrice1;
    private javax.swing.JLabel lbItemPrice2;
    private javax.swing.JLabel lbhotelname;
    private javax.swing.JLabel lbmenuitems;
    private javax.swing.JLabel lbmmt;
    private javax.swing.JTextField menuitemtxt;
    private javax.swing.JTable menutable;
    private javax.swing.JButton modbut;
    private javax.swing.JTextField txtmip;
    private javax.swing.JTextField txtmiq;
    private javax.swing.JTextField txtmmt;
    // End of variables declaration//GEN-END:variables
}