/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Product;

/**
 *
 * @author bhuva
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Product product;
    
    public ViewJPanel(Product product) {
        initComponents();
        this.product = product;
        displayProduct();
    }

    ViewJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVehicleId1 = new javax.swing.JLabel();
        txtDeviceIdentifierNumber = new javax.swing.JTextField();
        lblDeviceId1 = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lblLinkedinId1 = new javax.swing.JLabel();
        lblIpAddress1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPersonalIdentityNumber = new javax.swing.JTextField();
        txtIpAddress = new javax.swing.JTextField();
        lblFingerPrint1 = new javax.swing.JLabel();
        lblFacialPhoto1 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFaxNumber = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        lblDateOfBirth1 = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        lblMedicalRecordNumber1 = new javax.swing.JLabel();
        lblFaxNumber1 = new javax.swing.JLabel();
        txtHealthPlanBeneficiaryNumber = new javax.swing.JTextField();
        lblEmailId1 = new javax.swing.JLabel();
        lblHealthPlanBeneficiaryNumber1 = new javax.swing.JLabel();
        lblSocialSecurityNumber1 = new javax.swing.JLabel();
        txtBankAccountNumber = new javax.swing.JTextField();
        lblPersonalIdentityNumber1 = new javax.swing.JLabel();
        lblBankAccountNumber1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        lblLicenseNumber1 = new javax.swing.JLabel();
        txtVehicleIdentifierNumber = new javax.swing.JTextField();
        imgFingerPrint = new javax.swing.JLabel();
        imgFacialPhoto = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 1, true));

        lblVehicleId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVehicleId1.setText("Vehicle ID :");

        txtDeviceIdentifierNumber.setText("Device ID");
        txtDeviceIdentifierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifierNumberActionPerformed(evt);
            }
        });
        txtDeviceIdentifierNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeviceIdentifierNumberKeyTyped(evt);
            }
        });

        lblDeviceId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDeviceId1.setText("Device ID :");

        txtLinkedIn.setText("LinkedIn ID");
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyTyped(evt);
            }
        });

        lblLinkedinId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLinkedinId1.setText("LinkedIn ID :");

        lblIpAddress1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIpAddress1.setText("IP Address :");

        txtAddress.setText("Address");
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });

        txtPersonalIdentityNumber.setText("Personal Identity Number");
        txtPersonalIdentityNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonalIdentityNumberActionPerformed(evt);
            }
        });
        txtPersonalIdentityNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPersonalIdentityNumberKeyTyped(evt);
            }
        });

        txtIpAddress.setText("IP Address");
        txtIpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpAddressActionPerformed(evt);
            }
        });
        txtIpAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIpAddressKeyTyped(evt);
            }
        });

        lblFingerPrint1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFingerPrint1.setText("FingerPrint :");

        lblFacialPhoto1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFacialPhoto1.setText("Facial Photo :");

        txtPhoneNumber.setText("Phone Number");
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });

        txtFaxNumber.setText("FAX Number");
        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });
        txtFaxNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFaxNumberKeyTyped(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Product");

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblName1.setText("Name :");

        txtEmailId.setText("Email ID");
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        txtEmailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailIdKeyTyped(evt);
            }
        });

        txtDateOfBirth.setText("DD/MM/YYYY");
        txtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfBirthActionPerformed(evt);
            }
        });
        txtDateOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDateOfBirthKeyTyped(evt);
            }
        });

        lblAddress1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAddress1.setText("Address :");

        txtSocialSecurityNumber.setText("Social Security Number");
        txtSocialSecurityNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocialSecurityNumberActionPerformed(evt);
            }
        });
        txtSocialSecurityNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSocialSecurityNumberKeyTyped(evt);
            }
        });

        lblDateOfBirth1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDateOfBirth1.setText("Date Of Birth :");

        txtMedicalRecordNumber.setText("Medical Record Number");
        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });
        txtMedicalRecordNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedicalRecordNumberKeyTyped(evt);
            }
        });

        lblPhoneNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhoneNumber1.setText("Phone Number :");

        lblMedicalRecordNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMedicalRecordNumber1.setText("MRN :");

        lblFaxNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFaxNumber1.setText("FAX Number :");

        txtHealthPlanBeneficiaryNumber.setText("Health Plan Beneficiary Number");
        txtHealthPlanBeneficiaryNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthPlanBeneficiaryNumberActionPerformed(evt);
            }
        });
        txtHealthPlanBeneficiaryNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHealthPlanBeneficiaryNumberKeyTyped(evt);
            }
        });

        lblEmailId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmailId1.setText("Email ID :");

        lblHealthPlanBeneficiaryNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHealthPlanBeneficiaryNumber1.setText("HPBN :");

        lblSocialSecurityNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSocialSecurityNumber1.setText("SSN :");

        txtBankAccountNumber.setText("Bank A/c Number");
        txtBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumberActionPerformed(evt);
            }
        });
        txtBankAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBankAccountNumberKeyTyped(evt);
            }
        });

        lblPersonalIdentityNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPersonalIdentityNumber1.setText("PIN :");

        lblBankAccountNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankAccountNumber1.setText("Bank A/C Number :");

        txtName.setText("Name");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtLicenseNumber.setText("License Number");
        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });
        txtLicenseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLicenseNumberKeyTyped(evt);
            }
        });

        lblLicenseNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLicenseNumber1.setText("License Number :");

        txtVehicleIdentifierNumber.setText("Vehicle ID");
        txtVehicleIdentifierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentifierNumberActionPerformed(evt);
            }
        });
        txtVehicleIdentifierNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVehicleIdentifierNumberKeyTyped(evt);
            }
        });

        imgFingerPrint.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imgFingerPrintAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFingerPrint1)
                    .addComponent(lblLicenseNumber1)
                    .addComponent(lblName1)
                    .addComponent(lblVehicleId1)
                    .addComponent(lblDeviceId1)
                    .addComponent(lblHealthPlanBeneficiaryNumber1)
                    .addComponent(lblMedicalRecordNumber1)
                    .addComponent(lblLinkedinId1)
                    .addComponent(lblIpAddress1)
                    .addComponent(lblSocialSecurityNumber1)
                    .addComponent(lblEmailId1)
                    .addComponent(lblFaxNumber1)
                    .addComponent(lblPhoneNumber1)
                    .addComponent(lblDateOfBirth1)
                    .addComponent(lblAddress1)
                    .addComponent(lblBankAccountNumber1)
                    .addComponent(lblPersonalIdentityNumber1)
                    .addComponent(lblFacialPhoto1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHealthPlanBeneficiaryNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVehicleIdentifierNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDeviceIdentifierNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIpAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPersonalIdentityNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgFingerPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgFacialPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(225, 225, 225))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth1)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber1)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNumber1)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailId1)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSecurityNumber1)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecordNumber1)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanBeneficiaryNumber1)
                    .addComponent(txtHealthPlanBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountNumber1)
                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNumber1)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleId1)
                    .addComponent(txtVehicleIdentifierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceId1)
                    .addComponent(txtDeviceIdentifierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedinId1)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIpAddress1)
                    .addComponent(txtIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFingerPrint1)
                        .addGap(80, 80, 80))
                    .addComponent(imgFingerPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFacialPhoto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgFacialPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalIdentityNumber1)
                    .addComponent(txtPersonalIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDeviceIdentifierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierNumberActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPersonalIdentityNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonalIdentityNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonalIdentityNumberActionPerformed

    private void txtIpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpAddressActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtFaxNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtFaxNumberKeyTyped

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthActionPerformed

    private void txtSocialSecurityNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocialSecurityNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocialSecurityNumberActionPerformed

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtHealthPlanBeneficiaryNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberActionPerformed

    private void txtBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumberActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtVehicleIdentifierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierNumberActionPerformed

    private void imgFingerPrintAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imgFingerPrintAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_imgFingerPrintAncestorAdded

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtDateOfBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateOfBirthKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtDateOfBirthKeyTyped

    private void txtEmailIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailIdKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailIdKeyTyped

    private void txtSocialSecurityNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSocialSecurityNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtSocialSecurityNumberKeyTyped

    private void txtMedicalRecordNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtMedicalRecordNumberKeyTyped

    private void txtHealthPlanBeneficiaryNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberKeyTyped

    private void txtBankAccountNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccountNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtBankAccountNumberKeyTyped

    private void txtLicenseNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtLicenseNumberKeyTyped

    private void txtVehicleIdentifierNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtVehicleIdentifierNumberKeyTyped

    private void txtDeviceIdentifierNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtDeviceIdentifierNumberKeyTyped

    private void txtLinkedInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtLinkedInKeyTyped

    private void txtIpAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIpAddressKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtIpAddressKeyTyped

    private void txtPersonalIdentityNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersonalIdentityNumberKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((Character.isDigit(value))||(Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_txtPersonalIdentityNumberKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFacialPhoto;
    private javax.swing.JLabel imgFingerPrint;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblBankAccountNumber1;
    private javax.swing.JLabel lblDateOfBirth1;
    private javax.swing.JLabel lblDeviceId1;
    private javax.swing.JLabel lblEmailId1;
    private javax.swing.JLabel lblFacialPhoto1;
    private javax.swing.JLabel lblFaxNumber1;
    private javax.swing.JLabel lblFingerPrint1;
    private javax.swing.JLabel lblHealthPlanBeneficiaryNumber1;
    private javax.swing.JLabel lblIpAddress1;
    private javax.swing.JLabel lblLicenseNumber1;
    private javax.swing.JLabel lblLinkedinId1;
    private javax.swing.JLabel lblMedicalRecordNumber1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPersonalIdentityNumber1;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblSocialSecurityNumber1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleId1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDeviceIdentifierNumber;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtHealthPlanBeneficiaryNumber;
    private javax.swing.JTextField txtIpAddress;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPersonalIdentityNumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtVehicleIdentifierNumber;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
    txtName.setText(product.getName());
    txtAddress.setText(product.getAddress());
    txtDateOfBirth.setText(product.getDateOfBirth());
    txtPhoneNumber.setText(String.valueOf(product.getPhoneNumber()));     
    txtFaxNumber.setText(String.valueOf(product.getFaxNumber()));       
    txtEmailId.setText(product.getEmail());  
    txtSocialSecurityNumber.setText(String.valueOf(product.getSocialSecurityNumber()));       
    txtMedicalRecordNumber.setText(String.valueOf(product.getMedicalRecordNumber()));       
    txtHealthPlanBeneficiaryNumber.setText(String.valueOf(product.getHealthPlanBeneficiaryNumber()));
    txtBankAccountNumber.setText(String.valueOf(product.getBankAccountNumber()));
    txtLicenseNumber.setText(String.valueOf(product.getLicenseNumber()));
    txtVehicleIdentifierNumber.setText(String.valueOf(product.getVehicleIdentifierNumber()));
    txtDeviceIdentifierNumber.setText(String.valueOf(product.getDeviceIdentifierNumber()));
    txtLinkedIn.setText(product.getLinkedIn());
    txtIpAddress.setText(product.getIpAddress()); 
    txtPersonalIdentityNumber.setText(String.valueOf(product.getPin()));
    ImageIcon outputFacialPhoto = new ImageIcon(product.getFacialPhoto());
    Image finalOutputFacialPhoto = outputFacialPhoto.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
    imgFacialPhoto.setIcon(new ImageIcon(finalOutputFacialPhoto));
    ImageIcon outputFingerPrintPhoto= new ImageIcon(product.getFingerPrint());
    Image finalOutputFingerPrintPhoto = outputFingerPrintPhoto.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
    imgFingerPrint.setIcon(new ImageIcon(finalOutputFingerPrintPhoto));
    }
}
