/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineRole;

import Business.Vaccine.VaccineDirectory;
import Business.Medicine.MedicinesDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Variant.VariantDirect;
import Business.Network.Network;
import Business.Organization.ClinicOrganization;
import Business.Organization.MedicineOrganization;
import Business.Organization.Organization;
import Business.Organization.VaccineOrganization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.ClinicalTrialWorkRequest;
import Business.WorkQueue.MedicineWorkRequest;
import Business.WorkQueue.VaccineWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author bhuva
 */
public class ClinicalTrialResultsJpanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization vaccineOrganization;
    private MedicinesDirectory dl;
    private VariantDirect variantDirectory;
    private VaccineDirectory vaccineDirectory;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(ClinicalTrialResultsJpanel.class);
    private static final String CLASS_NAME = ClinicalTrialResultsJpanel.class.getName();

    /**
     * Creates new form LabResultsJpanel
     */
    public ClinicalTrialResultsJpanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Organization vaccineOrganization, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.vaccineOrganization = (VaccineOrganization) vaccineOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        this.dl = dl;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        assignBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Age", "Sex", "Message", "Sender", "Status", "Sample"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(30);
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 71, 589, 200));

        backBtn.setBackground(new java.awt.Color(0, 0, 255));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 82, 31));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COVID-19 LAB TEST AND CLINICAL TRIAL RESULTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 29, 585, -1));

        assignBtn.setBackground(new java.awt.Color(0, 0, 255));
        assignBtn.setForeground(new java.awt.Color(255, 255, 255));
        assignBtn.setText("SUBMIT");
        assignBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 72, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/result.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 480, 550));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 220, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDITIONAL INFORMATION ON VIRUS SAMPLE:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
            model.setRowCount(0);

            for (WorkRequest request : vaccineOrganization.getWQ().getWorkRequestList()) {

                if (request instanceof VaccineWorkRequest) {

                    Object[] row = new Object[8];
                    row[0] = ((VaccineWorkRequest) request);

                    row[1] = ((VaccineWorkRequest) request).getPatient().getAge();

                    row[2] = ((VaccineWorkRequest) request).getPatient().getSex();

                    row[3] = request.getMessage();

                    row[4] = request.getReceiver();

                    row[5] = request.getStatus();

                    String result = ((VaccineWorkRequest) request).getPatient().getNewVariantHistory().getVariantHistory().getVariantName();

                    if (request.getReceiver() == null || request.getReceiver().equals("Processing")) {
                        row[6] = null;
                    } else {
                        row[6] = ((VaccineWorkRequest) request).getPatient().getNewVariantHistory().getVariantHistory().getVariantName();
                    }

                    model.addRow(row);
                }

            }
        } catch (Exception e) {
            System.out.println("cliical trial result talble is yet to get data");
        }


    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VaccineWorkArea dwjp = (VaccineWorkArea) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else if (txtMessage.getText() != null) {
            String message = txtMessage.getText();
            JOptionPane.showMessageDialog(null, "Information for " + workRequestJTable.getValueAt(selectedRow, 6) + " has been updated. ");
        }


    }//GEN-LAST:event_assignBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

}
