/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.DoctorClass.Doctor;
import Business.DoctorClass.OrderList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author deepa
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Doctor doctor;
    private OrderList list;
    private DoctorWorkRequest docreq;
    private Network network;
    private EcoSystem system;
    private static Logger log = Logger.getLogger(DoctorWorkAreaJPanel.class);
    private static final String CLASS_NAME = DoctorWorkAreaJPanel.class.getName();

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();

    }

    public void network() {
        network.getName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrecriptionBtn = new javax.swing.JButton();
        labTestBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrecriptionBtn.setBackground(new java.awt.Color(0, 0, 255));
        PrecriptionBtn.setForeground(new java.awt.Color(255, 255, 255));
        PrecriptionBtn.setText("WRITE PRESCRIPTIONS");
        PrecriptionBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PrecriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecriptionBtnActionPerformed(evt);
            }
        });
        add(PrecriptionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 221, 49));

        labTestBtn.setBackground(new java.awt.Color(0, 0, 255));
        labTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        labTestBtn.setText("COVID-19 VARIANT TEST & CLINICAL TRIALS");
        labTestBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        labTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labTestBtnActionPerformed(evt);
            }
        });
        add(labTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 513, -1, 56));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor-3.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 66, 534, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/prescription.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/test.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 356, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void PrecriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecriptionBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor role");
        userProcessContainer.add("PrescriptionJPanel", new userinterface.DoctorRole.AddPrescriptionMedicineJPanel(userProcessContainer, list, userAccount, enterprise, organization, system, network));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_PrecriptionBtnActionPerformed

    private void labTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labTestBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor's lab request");
        userProcessContainer.add("TestJPanel", new userinterface.DoctorRole.DoctorRequestJpanel(userProcessContainer, userAccount, organization, enterprise, system, network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_labTestBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrecriptionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton labTestBtn;
    // End of variables declaration//GEN-END:variables
}
