/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyRole;

import Business.Enterprise.Enterprise;
import Business.MedicalInventory.MedicalInventory;
import Business.MedicalInventory.MedicalInventoryList;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author deepa
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsJPanel
     */
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private MedicalInventoryList medInvList;
    private Organization org;
    private PharmacyOrganization pharmorg;
    private MedicalInventory mi;
    private static Logger log = Logger.getLogger(ViewDetailsJPanel.class);
    private static final String CLASS_NAME = ViewDetailsJPanel.class.getName();

    public ViewDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, MedicalInventory mi) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.pharmorg = pharmorg;
        this.mi = mi;
        serialNumTxtField.setText(String.valueOf(mi.getRollNum()));
        availQuantityTxtField.setText(String.valueOf(mi.getQtyAvail()));
        drugNameTxtField.setText(mi.getMedName());
        saveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNumLbl = new javax.swing.JLabel();
        serialNumTxtField = new javax.swing.JTextField();
        drugLbl = new javax.swing.JLabel();
        drugNameTxtField = new javax.swing.JTextField();
        availLbl = new javax.swing.JLabel();
        availQuantityTxtField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        medicineLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialNumLbl.setForeground(new java.awt.Color(255, 255, 255));
        serialNumLbl.setText("SERIAL NUMBER:");
        add(serialNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 142, -1, -1));

        serialNumTxtField.setEditable(false);
        add(serialNumTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 167, -1));

        drugLbl.setForeground(new java.awt.Color(255, 255, 255));
        drugLbl.setText("MEDICINE NAME:");
        add(drugLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 173, -1, -1));

        drugNameTxtField.setEditable(false);
        add(drugNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 167, -1));

        availLbl.setForeground(new java.awt.Color(255, 255, 255));
        availLbl.setText("AVAILABILITY:");
        add(availLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        availQuantityTxtField.setEditable(false);
        availQuantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availQuantityTxtFieldActionPerformed(evt);
            }
        });
        add(availQuantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 106, -1));

        updateButton.setBackground(new java.awt.Color(0, 0, 255));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 75, 31));

        saveButton.setBackground(new java.awt.Color(0, 0, 255));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 65, 31));

        backButton.setBackground(new java.awt.Color(0, 0, 255));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 72, 31));

        medicineLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        medicineLbl.setForeground(new java.awt.Color(255, 255, 255));
        medicineLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineLbl.setText("MEDICINE INFORMATION");
        add(medicineLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 86, 279, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vitamin.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 36, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void availQuantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availQuantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availQuantityTxtFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        drugNameTxtField.setEditable(true);
        serialNumTxtField.setEditable(true);
        availQuantityTxtField.setEditable(true);
        updateButton.setEnabled(false);
        saveButton.setEnabled(true);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        if (drugNameTxtField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter a valid medicine name");
            return;
        }
        mi.setMedName(drugNameTxtField.getText());
        try {
            int availableQuantity = Integer.parseInt(availQuantityTxtField.getText());
            mi.setQtyAvail(availableQuantity);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }
        try {
            int serialNumber = Integer.parseInt(serialNumTxtField.getText());
            mi.setRollNum(serialNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }

        drugNameTxtField.setEditable(false);
        serialNumTxtField.setEditable(false);
        availQuantityTxtField.setEditable(false);
        saveButton.setEnabled(false);
        updateButton.setEnabled(true);
        log.debug(userAccount + " " + " updated the medicine details");

        JOptionPane.showMessageDialog(null, "Medicine updated Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmacyWorkArea me = (PharmacyWorkArea) component;
        me.reorderTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availLbl;
    private javax.swing.JTextField availQuantityTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel drugLbl;
    private javax.swing.JTextField drugNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel medicineLbl;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel serialNumLbl;
    private javax.swing.JTextField serialNumTxtField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
