/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhuva
 */
public class ManageDeliverymenpanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization restOrganization;

    public ManageDeliverymenpanel(JPanel userProcessContainer, EcoSystem system, Organization restOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.restOrganization = restOrganization;
        populatetable();
    }

    public void populatetable(){
        DefaultTableModel defaulttabledel = (DefaultTableModel) tablemandel.getModel();
        defaulttabledel.setRowCount(0);
        if(system.getDeliveryManDirectory().getDeliveryMan()!=null){
            for(DeliveryMan dm : system.getDeliveryManDirectory().getDeliveryMan()){
                Object row[] = new Object[3];
                row[0] = dm;
                row[1] = dm.getDeliveryusername();
                row[2] = dm.getRating();
                defaulttabledel.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btdeldelivery = new javax.swing.JButton();
        btcreatedel = new javax.swing.JButton();
        titlemandel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemandel = new javax.swing.JTable();
        btback = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btdeldelivery.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btdeldelivery.setText("Delete Delivery man");
        btdeldelivery.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btdeldelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeldeliveryActionPerformed(evt);
            }
        });
        add(btdeldelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 226, -1, -1));

        btcreatedel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btcreatedel.setText("Create Deliverymen");
        btcreatedel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btcreatedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreatedelActionPerformed(evt);
            }
        });
        add(btcreatedel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 226, -1, -1));

        titlemandel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlemandel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlemandel.setText("Manage Delivery Man");
        add(titlemandel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 651, 42));

        tablemandel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablemandel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 102, -1, 95));

        btback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btback.setText("Back");
        btback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 226, -1, -1));

        btupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btupdate.setText("Update Deliverymen");
        btupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });
        add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fourth.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] component = this.userProcessContainer.getComponents();
        for(Component comp : component){
            if(comp instanceof SystemAdminWorkAreaJPanel){
                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                systemAdminWorkAreaJPanel.populateTree(); 
            }
        } 
    }//GEN-LAST:event_btbackActionPerformed

    private void btcreatedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreatedelActionPerformed
        NewDeliverymenPanel createdel = new NewDeliverymenPanel(userProcessContainer, system);
        userProcessContainer.add("NewCustomerPanel", createdel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        populatetable();
    }//GEN-LAST:event_btcreatedelActionPerformed

    private void btdeldeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeldeliveryActionPerformed
       int selectedRow = tablemandel.getSelectedRow();
       if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
       }
       DeliveryMan dm = (DeliveryMan)tablemandel.getValueAt(selectedRow,0);
       system.getDeliveryManDirectory().deleteDeliveryMan(dm);
       populatetable();
       JOptionPane.showMessageDialog(null, "Delivery man account deleted Successfully");
    }//GEN-LAST:event_btdeldeliveryActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        int selectedRow = tablemandel.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DeliveryMan dm = (DeliveryMan)tablemandel.getValueAt(selectedRow,0);
        ViewDeliverymanPanel updateDeliveryJPanel = new ViewDeliverymanPanel(userProcessContainer, system, restOrganization, dm);
        userProcessContainer.add("CreateCustomer", updateDeliveryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btcreatedel;
    private javax.swing.JButton btdeldelivery;
    private javax.swing.JButton btupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablemandel;
    private javax.swing.JLabel titlemandel;
    // End of variables declaration//GEN-END:variables
}
