/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bhuva
 */
public class ViewCustomerPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization custorganization;
    private UserAccount useracc;
    private Employee employee;

    public ViewCustomerPanel(JPanel userProcessContainer, EcoSystem system, Organization custorganization, UserAccount useracc, Employee employee) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.custorganization = custorganization;
        this.useracc= useracc;
        this.employee=employee;
        initComponents();
        cusvnametxt.setText(employee.getName());
        cusvusernametxt.setText(useracc.getUsername());
        cusvpasswordtxt.setText(useracc.getPassword());
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbcusvpassword = new javax.swing.JLabel();
        lbcusvusername = new javax.swing.JLabel();
        lbcusvemailid = new javax.swing.JLabel();
        cusvnametxt = new javax.swing.JTextField();
        cusvusernametxt = new javax.swing.JTextField();
        cusvemailtxt = new javax.swing.JTextField();
        btsave = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        cusvpasswordtxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 600, 42));

        lbname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbname.setText("Name:");
        add(lbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 111, -1, -1));

        lbcusvpassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbcusvpassword.setText("Password:");
        add(lbcusvpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 211, -1, -1));

        lbcusvusername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbcusvusername.setText("Username:");
        add(lbcusvusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 161, -1, -1));

        lbcusvemailid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbcusvemailid.setText("Email ID:");
        add(lbcusvemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 261, -1, -1));
        add(cusvnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 113, 200, -1));

        cusvusernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusvusernametxtActionPerformed(evt);
            }
        });
        add(cusvusernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 163, 200, -1));
        add(cusvemailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 263, 200, -1));

        btsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btsave.setText("Update");
        btsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 311, 65, -1));

        btback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btback.setText("Back");
        btback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 311, -1, -1));
        add(cusvpasswordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 213, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fourth.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void cusvusernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusvusernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusvusernametxtActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCustomerPanel){
                ManageCustomerPanel manageCustomersJPanel= (ManageCustomerPanel) comp;
               manageCustomersJPanel.populatetable(); 
            }
        }
    }//GEN-LAST:event_btbackActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        try{
        if(cusvnametxt.getText().isEmpty()||cusvusernametxt.getText().isEmpty()||cusvemailtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please provide appropriate details to proceed");
        }
        String name = cusvnametxt.getText();
        String username = cusvusernametxt.getText();
        String password = cusvpasswordtxt.getText();
        String emailid = cusvemailtxt.getText();
        List<Organization> organizationcus =system.getCustomerDirectory().searchOrganization("Customer") ;
        for(Organization org : organizationcus){
          for(UserAccount u:org.getUserAccountDirectory().getUserAccountList()) {
                  u.setUsername(username);
                  u.setPassword(password);
              }
          JOptionPane.showMessageDialog(null, "Customer Updated Successfully");
        }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "Please provide appropriate details to proceed");
    }
    }//GEN-LAST:event_btsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btsave;
    private javax.swing.JTextField cusvemailtxt;
    private javax.swing.JTextField cusvnametxt;
    private javax.swing.JPasswordField cusvpasswordtxt;
    private javax.swing.JTextField cusvusernametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbcusvemailid;
    private javax.swing.JLabel lbcusvpassword;
    private javax.swing.JLabel lbcusvusername;
    private javax.swing.JLabel lbname;
    // End of variables declaration//GEN-END:variables
}
