/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Order.Order;
import Business.Order.OrderDirectory;
import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.menu.Menu;
import Business.menu.MenuDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.ViewCustomerPanel;

/**
 *
 * @author bhuva
 */
    public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private String quant;
    private UserAccount userAccount;
    private EcoSystem system;
    Menu menu;
    ArrayList<Menu> ml;
    DefaultTableModel defaulttablemodelcust;
    private String selectedRestaurantName;
    private Restaurant resObj;
    Double totalPrice;
    Order order;
    
    
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.ml = new ArrayList<>();
        this.totalPrice= 0.0;
        populateComboBox();
        tableListener();
    }

    
    public void tableListener(){
        defaulttablemodelcust = (DefaultTableModel) ordermenuitemtable.getModel();
        defaulttablemodelcust.setRowCount(0);
        defaulttablemodelcust.addTableModelListener(new TableModelListener()
            {
                public void tableChanged(TableModelEvent evt)
                { 
                    int coloum = evt.getColumn();
                    int row = evt.getFirstRow();
                    menu = (Menu)defaulttablemodelcust.getValueAt(row, 0);
                    quant = String.valueOf(defaulttablemodelcust.getValueAt(row,2));
                }
            });
    }
    
    public void populateMenuItems(String resName){
            resObj = system.getRestaurantDirectory().findRestaurant(resName);
            if(resObj!=null && resObj.getMd()!=null){
                for(Menu m : resObj.getMd().getMenu()) {
                    Object row[] = new Object[3];
                    row[0] = m;
                    row[1] = m.getItemPrice();
                    row[2] = m.getQuantity();
                    defaulttablemodelcust.addRow(row);
                }
            
        }
    }
    
    public void populateCartTable(){
        DefaultTableModel dtm = (DefaultTableModel) orderhistorytable.getModel();
        dtm.setRowCount(0);
        for(Order order : system.getOrderDirectory().getOrderhist()){
            Object row[] = new Object[5];
                row[0] = order.getOrderID();
                row[1] = order;
                row[2] = order.getRestaurant().getName();
                row[3] = order.getComments();
                row[4] = order.getAmount();
                dtm.addRow(row);
        }
        
    }
    public void populateOrderDetails(Order o){
        DefaultTableModel getorder = (DefaultTableModel) tracktable.getModel();
        getorder.setRowCount(0);
        for(Menu m : o.getMenuDirectory().getMenu()){
            Object row[] = new Object[3];
                row[0] = m;
                row[1] = m.getItemPrice();
                row[2] = m.getQuantity();
                getorder.addRow(row);
        }   
    }
    
    public void populateRequestTable() {
    }
       
    public void populateComboBox(){
         for(Restaurant res: system.getRestaurantDirectory().getRestaurantList()){
            selecthotelcombobox.addItem(res.getName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        selecthotelcombobox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordermenuitemtable = new javax.swing.JTable();
        addcartbt = new javax.swing.JButton();
        confirmorderbt = new javax.swing.JButton();
        lbtotalprice = new javax.swing.JLabel();
        tptxt = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        c = new javax.swing.JTextArea();
        trackorderbt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderhistorytable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tracktable = new javax.swing.JTable();
        viewbt = new javax.swing.JButton();
        orderrecievedbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 27, 127, 30));

        selecthotelcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hotel" }));
        selecthotelcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecthotelcomboboxActionPerformed(evt);
            }
        });
        add(selecthotelcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 35, 256, -1));

        ordermenuitemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ordermenuitemtable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 100, 487, 109));

        addcartbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addcartbt.setText("Add cart");
        addcartbt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addcartbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcartbtActionPerformed(evt);
            }
        });
        add(addcartbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 330, 66, -1));

        confirmorderbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        confirmorderbt.setText("Confirm Order");
        confirmorderbt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmorderbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmorderbtActionPerformed(evt);
            }
        });
        add(confirmorderbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 330, -1, -1));

        lbtotalprice.setText("    Total Price:");
        add(lbtotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 227, -1, 22));

        tptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tptxtKeyTyped(evt);
            }
        });
        add(tptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 228, 91, -1));

        c.setColumns(20);
        c.setRows(5);
        c.setText("Enter Comments:");
        jScrollPane4.setViewportView(c);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 227, 222, -1));

        trackorderbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        trackorderbt.setText("Track Order");
        trackorderbt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        trackorderbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackorderbtActionPerformed(evt);
            }
        });
        add(trackorderbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 330, -1, -1));

        orderhistorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Oder ID", "Order Status", "Restaurant Name", "Comments", "Total Price"
            }
        ));
        jScrollPane3.setViewportView(orderhistorytable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 401, 487, 113));

        tracktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(tracktable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 401, -1, 98));

        viewbt.setText("View Order");
        viewbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtActionPerformed(evt);
            }
        });
        add(viewbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 532, -1, -1));

        orderrecievedbt.setText("Order Recieved");
        orderrecievedbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderrecievedbtActionPerformed(evt);
            }
        });
        add(orderrecievedbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 532, 135, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Second.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void selecthotelcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecthotelcomboboxActionPerformed
        selectedRestaurantName = String.valueOf(selecthotelcombobox.getSelectedItem());
        populateMenuItems(selectedRestaurantName);        
    }//GEN-LAST:event_selecthotelcomboboxActionPerformed

    private void confirmorderbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmorderbtActionPerformed
        OrderDirectory orderdiretory;
        ArrayList<Order> oh;
        if(system.getOrderDirectory()==null){
             orderdiretory = new OrderDirectory();
        }else{
             orderdiretory = system.getOrderDirectory();
        }
        if(orderdiretory.getOrderhist()==null){
            oh = new ArrayList();
        }else{
            oh = orderdiretory.getOrderhist();
        }
        MenuDirectory md = new MenuDirectory();
        md.setMenu(ml);
        Order order = new Order();
        order.setMenuDirectory(md);
        order.setRestaurant(resObj);
        order.setUserAccount(userAccount);
        order.setAmount(totalPrice);
        order.setComments(c.getText());
        oh.add(order);
        orderdiretory.setOrderhist(oh);
        system.setOrderDirectory(orderdiretory);
        populateCartTable();
        JOptionPane.showMessageDialog(null,"Order Placed Successfully", "INFO", JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_confirmorderbtActionPerformed

    private void addcartbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcartbtActionPerformed
        int row = ordermenuitemtable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Row not selected");
            return;
        }
        Menu menucus = new Menu();
        MenuDirectory md = new MenuDirectory();        
        menucus.setItemName(String.valueOf(ordermenuitemtable.getValueAt(row,0)));
        menucus.setItemPrice(Double.parseDouble(String.valueOf(ordermenuitemtable.getValueAt(row,1))));
        menucus.setQuantity(Integer.parseInt(String.valueOf(ordermenuitemtable.getValueAt(row,2))));
        ml.add(menucus);
        totalPrice =totalPrice + (menucus.getItemPrice()* menucus.getQuantity());
        this.tptxt.setText(String.valueOf(totalPrice));
        JOptionPane.showMessageDialog(null,"Item added to cart. Please add more items or Place Order to Proceed", "INFO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addcartbtActionPerformed

    private void viewbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtActionPerformed
        int selectedRow = orderhistorytable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (Order)orderhistorytable.getValueAt(selectedRow,1);
        populateOrderDetails(order);
    }//GEN-LAST:event_viewbtActionPerformed

    private void trackorderbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackorderbtActionPerformed
       populateCartTable();
    }//GEN-LAST:event_trackorderbtActionPerformed

    private void orderrecievedbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderrecievedbtActionPerformed
        int selectedRow = orderhistorytable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (Order)orderhistorytable.getValueAt(selectedRow,1);
        order.setOrderStatus("Received");
        populateCartTable();
    }//GEN-LAST:event_orderrecievedbtActionPerformed

    private void tptxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tptxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))||(!Character.isAlphabetic(value))) {
            evt.consume();
        }
    }//GEN-LAST:event_tptxtKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcartbt;
    private javax.swing.JTextArea c;
    private javax.swing.JButton confirmorderbt;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbtotalprice;
    private javax.swing.JTable orderhistorytable;
    private javax.swing.JTable ordermenuitemtable;
    private javax.swing.JButton orderrecievedbt;
    private javax.swing.JComboBox<String> selecthotelcombobox;
    private javax.swing.JTextField tptxt;
    private javax.swing.JButton trackorderbt;
    private javax.swing.JTable tracktable;
    private javax.swing.JButton viewbt;
    // End of variables declaration//GEN-END:variables
}
